import fs from "fs/promises";
import path from "path";
import { glob } from "glob";

interface InternalRegistryItem {
  name: string;
  title: string;
  description: string;
  path: string;
  code: string;
  dependencies: string[];
  registryDependencies: string[];
}

const projectRoot = process.cwd();
const componentsPiecesDir = path.join(projectRoot, "components", "pieces");

const registryDir = path.join(projectRoot, "registry");
const internalRegistryTsPath = path.join(registryDir, "registry.internal.ts");

const getComponentName = (filePath: string) =>
  filePath.replace(/\.tsx$/, "").replace(/\//g, "-");

const toTitleCase = (kebab: string) =>
  kebab
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

const extractDependencies = (content: string) => {
  const importRegex = /import\s+(?:[\s\S]*?)\s+from\s+["']([^"']+)["']/g;
  const matches = [...content.matchAll(importRegex)].map((m) => m[1]);

  const dependencies = new Set<string>();
  const registryDependencies = new Set<string>();

  for (const imp of matches) {
    if (imp.startsWith(".")) continue;
    if (imp.startsWith("@/")) {
      if (imp.includes("/utils")) registryDependencies.add("cn");
      continue;
    }
    dependencies.add(imp.split("/")[0]);
  }

  if (/from\s+["']react["']/.test(content) || content.includes("useState(")) {
    dependencies.add("react");
  }

  return {
    dependencies: Array.from(dependencies),
    registryDependencies: Array.from(registryDependencies),
  };
};

async function buildInternalRegistry() {
  console.log("🔍 Starting internal registry build...");

  await fs.mkdir(registryDir, { recursive: true });

  const registry: Record<string, InternalRegistryItem> = {};
  const componentFiles = await glob("**/*.tsx", { cwd: componentsPiecesDir });

  for (const file of componentFiles) {
    const absPath = path.join(componentsPiecesDir, file);
    const content = await fs.readFile(absPath, "utf8");

    const { dependencies, registryDependencies } = extractDependencies(content);
    const kebabName = getComponentName(file);
    const title = toTitleCase(kebabName);

    registry[kebabName] = {
      name: kebabName,
      title,
      description: `A ${title} component for internal documentation.`,
      path: path.relative(projectRoot, absPath),
      code: content,
      dependencies,
      registryDependencies,
    };

    console.log(`✅ Processed: ${title}`);
  }

  // 🧩 Generate TypeScript file instead of JSON
  const fileContent = `// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by buildInternalRegistry.ts

export const registryData = ${JSON.stringify(registry, null, 2)} as const;

export default registryData;
`;

  await fs.writeFile(internalRegistryTsPath, fileContent, "utf8");

  console.log(
    `\n🎉 registry.internal.ts built successfully at ${internalRegistryTsPath}`
  );
  console.log(`Total components: ${Object.keys(registry).length}`);
}

buildInternalRegistry().catch((error) => {
  console.error("❌ Error building internal registry:", error);
  process.exit(1);
});
